version: '2'

services:
  storage:
    image: openzipkin/zipkin-elasticsearch7
    container_name: elasticsearch
    ports: 
      - "127.0.0.1:9200:9200"
    networks: 
      - zipkin
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=elasticsearch:9200
      # - ES_USERNAME=#####
      # - ES_PASSWORD=#####
    ports:
      - "127.0.0.1:9411:9411"
    networks:
      - zipkin

  dependencies:
    image: openzipkin/zipkin-dependencies
    container_name: dependencies
    entrypoint: crond -f
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=elasticsearch:9200
      # - ES_USERNAME=#####
      # - ES_PASSWORD=#####
      # - JAVA_OPTS=-verbose:gc -Xms1G -Xmx1G
    networks:
      - zipkin

networks:
  zipkin:
    driver: bridge
      